
server:
  port: 8090
#多数据库配置
spring:
  datasource:
    dynamic:
      primary: mysql #默认的数据库
      datasource:
        mysql:
          url: jdbc:mysql://localhost:3306/wms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: 123456
        oracle:
          url: jdbc:oracle:thin:@bysprod.bys.com:1521:BYSPROD
          username: apps
          password: apps
          driver-class-name: oracle.jdbc.OracleDriver

      # HikariCP配置项
      hikari:
          minimum-idle: 5
          maximum-pool-size: 20
          idle-timeout: 30000
          pool-name: OracleHikariCP
          max-lifetime: 2000000
          connection-timeout: 30000
  # MyBatis配置
mybatis-plus:
  mapper-locations:
    - classpath:/mapper/mysql/*.xml
    - classpath:/mapper/oracle/*.xml
  type-aliases-package: com.wms.entity
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null

Logging:
  level:
    org.apache.ibatis: DEBUG
    com.baomidou.mybatisplus: DEBUG
    com.wms: debug